### PR TITLE
Push o11c's wip branch onto newdev

### PR DESCRIPTION
**Pull request by CrazyPython**
He'll be gone for a few days, so let's further his progress.

### CODE REVIEW

**Comment by CrazyPython** [comment]
Yeah! deleted absolutely everything on newdev!

Hopefully git will be more cooperative after this...

**Comment by CrazyPython** [comment]
@casperdcl Any idea how to force a merge on GitHub or w/ the command line? 😕

**Comment by casperdcl** [comment]
like this?

**Comment by CrazyPython** [comment]
@casperdcl Yes, like that. Now we need to work on merging main with o11c's progress.

**Pull request merged**
