### PR TITLE
Create project skeleton

### PR DESCRIPTION
**Pull request by o11c**
Currently not attempt to do any distribution - whether single-header or `make install`.

Tests will likely change somewhat when we use a real test harness.

### CODE REVIEW

**Comment by CrazyPython** [comment]
@o11c why remove most of the the .gitignore?

**Comment by CrazyPython** [comment]
@o11c I think this is ready to merge other than the .gitignore part (CLion is my IDE, that's why the IntelliJ stuff is there). BUT into the dev branch.

**Comment by o11c** [comment]
It is wrong to use a project's .gitignore for user-specific backup/configuration files - it should only contain patterns for things that can be made using the Makefile.

You should instead add those patterns to either ~/.gitignore or .git/info/exclude.

**Comment by o11c** [comment]
Note: it's actually `~/.config/git/ignore` by default these days.

Back in the days when there *was* no default, `~/.gitignore` was the recommendation for `core.excludesFile`

**Comment by CrazyPython** [comment]
@o11c I'm going to merge because there aren't any problems

**Pull request merged**
