### PR TITLE
range fix

### PR DESCRIPTION
**Pull request by adrian17**

### CODE REVIEW

**Comment by adrian17** [comment]
eh, once again just after a new commit...

**Comment by adrian17** [comment]
(will rebase in a sec)

**Comment by adrian17** [comment]
there.

**Comment by adrian17** [comment]
...well that's a wrong button

**Comment by casperdcl** [comment]
This is a different mutable from the one I was talking about. Incidentally, this PR would surely break thingd like `const RangeIterator &operator++() const `

**Comment by adrian17** [comment]
...oh, I didn't even notice it.

Wat. Const operator++ dosn't make any sense in the first place, so the best fix would be to remove it.

**Comment by adrian17** [comment]
Updated with mutable/const removals.

**Comment by CrazyPython** [comment]
@adrian17 does this use the remove const thing I was talking about? You can also do add const, add volatile, and remove volatile.

**Comment by adrian17** [comment]
>  does this use the remove const thing I was talking about?

AFAIK it's not necessary.

Let's wait for @casperdcl  to review it.

**Comment by casperdcl** [comment]
const operator ++ was my way of supporting const_iterator. That is, an iterator which does not allow changing of the underlying object, but does allow the pointer to be incremented @adrian17. does that not make sense?

**Comment by adrian17** [comment]
They still don't have anything to do with each other.

Everything would work perfectly if

1.it properly used all iterator's aliases, like `reference`, instead of dropping to `value_type&`, which drops the const.

2.It changed this:

	template <typename _Container,
	          typename _Tqdm = Tqdm<typename _Container::iterator>>
	_Tqdm tqdm(_Container &v) {
	  return _Tqdm(v);
	}

	template <size_t N, typename T, typename _Tqdm = Tqdm<T *>>
	_Tqdm tqdm(T (&tab)[N]) {
	  return _Tqdm(tab, N);
	}

To:

	template <typename _Container,
	          typename _Iter = decltype(std::begin(std::declval<_Container &>())),
	          typename _Tqdm = Tqdm<_Iter>>
	_Tqdm tqdm(_Container& v) {
	  return _Tqdm(v);
	}

(that may be simplified more, but I didn't have more time to think about it)

I had a full fix going, but I forgot to pull from the dev and now I don't have time to rebase it, and I won't be able to for the next week.

**Comment by casperdcl** [comment]
@adrian17 are you happy withthe current implementation in the dev branch? Feel free to open another PR there - even if it's minor

**Pull request closed without merging**
