### PR TITLE
Range and array support

### PR DESCRIPTION
**Pull request by adrian17**
...and some other minor improvements.

### CODE REVIEW

**Comment by CrazyPython** [comment]
@adrian17 Hello! Why'd you close? wanna join us in chat?

**Comment by adrian17** [comment]
With the latest dev commits/PRs I realized I may not be the target audience for this.

Anyway, the third commit (with operator bool) would be easy to adapt.

**Comment by CrazyPython** [comment]
@adrian17 huh? target audience? We could use another developer.

**Comment by casperdcl** [comment]
this was good stuff, I think I added most of it in parallel to the dev branch... going to still review it.

**Comment by CrazyPython** [comment]
@adrian17 Don't be shy. This was created 2 days ago, we need all the help we* can get! 

\**CrazyPython is not affiliated with `tqdm` in any way. He has write access, but really is just a dev walking down the street that sorta just propsed this entire project on GitHub issues.*

**Comment by casperdcl** [comment]
James - both Stephen and I (and the rest of the world) have been wanting to port over to other languages for ages; your boundless enthusiasm pushed us over the edge. Did you see for example the (alpha) ruby port? https://github.com/powerpak/tqdm-ruby

**Comment by CrazyPython** [comment]
1. I like this open source adventure, and I'm ready to have another one
anytime.
2. Great to know! So looks like I domino effected the entirety of tqdm
ports? :P
3. nope, didn't see that.
4. How'd you get my real name?

**Comment by casperdcl** [comment]
merged ;)

**Pull request merged**
